FiendFolio.ITEM.ROCK = {
	--FiendFolio.ITEM.ROCK
	DIRT_CLUMP 					= Isaac.GetTrinketIdByName("Dirt Clump"),
	ROLLING_ROCK 				= Isaac.GetTrinketIdByName("Rolling Rock"),
	POCKET_SAND 				= Isaac.GetTrinketIdByName("Pocket Sand"),
	ROUGH_ROCK 					= Isaac.GetTrinketIdByName("Rough Rock"),
	BLOODY_ROCK 				= Isaac.GetTrinketIdByName("Bloody Rock"),
	SPIKED_ROCK 				= Isaac.GetTrinketIdByName("Spiked Rock"),
	SLIPPY_ROCK 				= Isaac.GetTrinketIdByName("Slippy Rock"),
	ARCANE_ROCK 				= Isaac.GetTrinketIdByName("Arcane Rock"),
	MINERAL_ROCK 				= Isaac.GetTrinketIdByName("Mineral Rock"),
	THORNY_ROCK 				= Isaac.GetTrinketIdByName("Thorny Rock"),
	TIME_LOST_DIAMOND 			= Isaac.GetTrinketIdByName("Time-lost Diamond"),
	OBSIDIAN_GRINDSTONE 		= Isaac.GetTrinketIdByName("Obsidian Grindstone"),
	GODS_MARBLE 				= Isaac.GetTrinketIdByName("God's Marble"),
	TWENTY_SIDED_EMERALD 		= Isaac.GetTrinketIdByName("Twenty-Sided Emerald"),
	TECHNOLOGICAL_RUBY_2 		= Isaac.GetTrinketIdByName("Technological Ruby 2.0"),
	LEAKY_ROCK 					= Isaac.GetTrinketIdByName("Leaky Rock"),
	TWIN_TUFFS 					= Isaac.GetTrinketIdByName("Twin Tuffs"),
	WETSTONE 					= Isaac.GetTrinketIdByName("Wetstone"),
	STROMATOLITE 				= Isaac.GetTrinketIdByName("Stromatolite"),
	RIBBED_ROCK 				= Isaac.GetTrinketIdByName("Ribbed Rock"),
	FIENDISH_AMETHYST 			= Isaac.GetTrinketIdByName("Fiendish Amethyst"),
	STURDY_ROCK 				= Isaac.GetTrinketIdByName("Sturdy Rock"),
	BRICK_ROCK 					= Isaac.GetTrinketIdByName("Brick Rock"),
	SAPPHIC_SAPPHIRE 			= Isaac.GetTrinketIdByName("Sapphic Sapphire"),
	BLOOD_DIAMOND 				= Isaac.GetTrinketIdByName("Blood Diamond"),
	SCENTED_ROCK 				= Isaac.GetTrinketIdByName("Scented Rock"),
	ARCADE_ROCK 				= Isaac.GetTrinketIdByName("Arcade Rock"),
	TINTED_HEART 				= Isaac.GetTrinketIdByName("Tinted Heart"),
	ROSE_QUARTZ 				= Isaac.GetTrinketIdByName("Rose Quartz"),
	HAILSTONE 					= Isaac.GetTrinketIdByName("Hailstone"),
	RAMBLIN_OPAL 				= Isaac.GetTrinketIdByName("Ramblin' Opal"),
	SAND_DOLLAR 				= Isaac.GetTrinketIdByName("Sand Dollar"),
	HENGE_ROCK 					= Isaac.GetTrinketIdByName("Henge Rock"),
	SALT_LAMP 					= Isaac.GetTrinketIdByName("Salt Lamp"),
	MOLTEN_SLAG 				= Isaac.GetTrinketIdByName("Molten Slag"),
	THUNDER_EGG 				= Isaac.GetTrinketIdByName("Thunder Egg"),
	UNOBTAINIUM 				= Isaac.GetTrinketIdByName("Unobtainium"),
	SANDSTONE 					= Isaac.GetTrinketIdByName("Sandstone"),
	FAKE_ROCK 					= Isaac.GetTrinketIdByName("Fake Rock"),
	CITRINE_PULP 				= Isaac.GetTrinketIdByName("Citrine Pulp"),
	BLOODSTONE 					= Isaac.GetTrinketIdByName("Bloodstone"),
	EMETIC_ANTIMONY 			= Isaac.GetTrinketIdByName("Emetic Antimony"),
	DOUBLE_RUBBLE 				= Isaac.GetTrinketIdByName("Double Rubble"),
	ROCK_FROM_AN_ABYSS 			= Isaac.GetTrinketIdByName("Rock from an Abyss"),
	HECTOR 						= Isaac.GetTrinketIdByName("Hector"),
	VESSEL_ROCK 				= Isaac.GetTrinketIdByName("Vessel Rock"),
	HALF_VESSEL_ROCK 			= Isaac.GetTrinketIdByName("Half Vessel Rock"),
	FULL_VESSEL_ROCK 			= Isaac.GetTrinketIdByName("Full Vessel Rock"),
	CONSTANT_ROCK_SHOOTER 		= Isaac.GetTrinketIdByName("Constant Rock Shooter"),
	ROBOT_ROCK 					= Isaac.GetTrinketIdByName("Robot Rock"),
	ROCK_CANDY 					= Isaac.GetTrinketIdByName("Rock Candy"),
	KEYSTONE 					= Isaac.GetTrinketIdByName("Keystone"),
	SILVER_TONGUE 				= Isaac.GetTrinketIdByName("Silver Tongue"),
	MEAT_SLAB 					= Isaac.GetTrinketIdByName("Meat Slab"),
	SHEEP_ROCK 					= Isaac.GetTrinketIdByName("Sheep Rock"),
	REBELLION_ROCK 				= Isaac.GetTrinketIdByName("Rebellion Rock"),
	DADS_LEGENDARY_GOLDEN_ROCK 	= Isaac.GetTrinketIdByName("Dad's Legendary Golden Rock"),
	BEDROCK 					= Isaac.GetTrinketIdByName("Bedrock"),
	SHEETROCK 					= Isaac.GetTrinketIdByName("Sheetrock"),
	FETAL_STONE 				= Isaac.GetTrinketIdByName("Fetal Stone"),
	FOCUS_CRYSTAL 				= Isaac.GetTrinketIdByName("Focus Crystal"),
	ODDLY_SMOOTH_STONE 			= Isaac.GetTrinketIdByName("Oddly Smooth Stone"),
	MOONSTONE 					= Isaac.GetTrinketIdByName("Moonstone"),
	LIMESTONE 					= Isaac.GetTrinketIdByName("Limestone"),
	CARNAL_CARNELIAN 			= Isaac.GetTrinketIdByName("Carnal Carnelian"),
	REBAR_ROCK 					= Isaac.GetTrinketIdByName("Rebar Rock"),
	DOGROCK_ROCK 				= Isaac.GetTrinketIdByName("Dogrock Rock"),
	STALACTITE 					= Isaac.GetTrinketIdByName("Stalactite"),
	CAST_GEM 					= Isaac.GetTrinketIdByName("Cast Gem"),
	SHARD_OF_GOLGOTHA 			= Isaac.GetTrinketIdByName("Shard of Golgotha"),
	SMOKY_QUARTZ 				= Isaac.GetTrinketIdByName("Smoky Quartz"),
	TWINKLING_ROCK 				= Isaac.GetTrinketIdByName("Twinkling Rock"),
	ROCK_CAKE 					= Isaac.GetTrinketIdByName("Rock Cake"),
	CHARCOAL 					= Isaac.GetTrinketIdByName("Charcoal"),
	ACHILLES_ROCK 				= Isaac.GetTrinketIdByName("Achilles' Rock"),
	ELECTRUM 					= Isaac.GetTrinketIdByName("Electrum"),
	PURE_QUARTZ 				= Isaac.GetTrinketIdByName("Pure Quartz"),
	AMAZONITE 					= Isaac.GetTrinketIdByName("Amazonite"),
	STAR_SAPPHIRE 				= Isaac.GetTrinketIdByName("Star Sapphire"),
	GRAVESTONE 					= Isaac.GetTrinketIdByName("Gravestone"),
	SAND_CASTLE 				= Isaac.GetTrinketIdByName("Sand Castle"),
	DAMAGED_SAND_CASTLE 		= Isaac.GetTrinketIdByName("Damaged Sand Castle"),
	BROKEN_SAND_CASTLE 			= Isaac.GetTrinketIdByName("Broken Sand Castle"),
	GUARDED_GARNET 				= Isaac.GetTrinketIdByName("Guarded Garnet"),
	SHAMROCK 					= Isaac.GetTrinketIdByName("Shamrock"),
	GAS_POCKET 					= Isaac.GetTrinketIdByName("Gas Pocket"),
	SOAP_STONE 					= Isaac.GetTrinketIdByName("Soap Stone"),
	SPIRIT_URN 					= Isaac.GetTrinketIdByName("Spirit Urn"),
	SUN_SHARD 					= Isaac.GetTrinketIdByName("Sun Shard"),
	STEADFAST_STONE 			= Isaac.GetTrinketIdByName("Steadfast Stone"),
	INSATIABLE_APATITE 			= Isaac.GetTrinketIdByName("Insatiable Apatite"),
	RAI_STONE 					= Isaac.GetTrinketIdByName("Rai Stone"),
	ORE_PENNY 					= Isaac.GetTrinketIdByName("Ore Penny"),
	HEAVY_METAL 				= Isaac.GetTrinketIdByName("Heavy Metal"),
	GROSSULAR 					= Isaac.GetTrinketIdByName("Grossular"),
	SULFUR_CRYSTAL 				= Isaac.GetTrinketIdByName("Sulfur Crystal"),
	TROLLITE 					= Isaac.GetTrinketIdByName("A Bit of Trollite"),
	THROWLOMITE 				= Isaac.GetTrinketIdByName("Throwlomite"),
	HEARTHSTONE 				= Isaac.GetTrinketIdByName("Hearthstone"),
	MAGNETIC_SAND 				= Isaac.GetTrinketIdByName("Magnetic Sand"),
	POWER_ROCK 					= Isaac.GetTrinketIdByName("Power Rock"),
	TIGERS_EYE 					= Isaac.GetTrinketIdByName("Tiger's Eye"),
	SMALLER_ROCK 				= Isaac.GetTrinketIdByName("Smaller Rock"),
	NITRO_CRYSTAL 				= Isaac.GetTrinketIdByName("Nitro Crystal"),
	SHARD_OF_GOLEM 				= Isaac.GetTrinketIdByName("Shard of Golem"),
	ROCK_WORM 					= Isaac.GetTrinketIdByName("Rock Worm"),
	FOOLS_UNOBTAINIUM 			= Isaac.GetTrinketIdByName("Fool's Unobtainium"),
	MINICHIBISIDIAN 			= Isaac.GetTrinketIdByName("Minichibisidian"),
	FRIENDLY_RAPID_FIRE_OPAL 	= Isaac.GetTrinketIdByName("Friendly Rapid Fire Opal"),
	HIDDENITE					= Isaac.GetTrinketIdByName("Hiddenite"),
	--Pebbles
	KNIFE_PEBBLE 				= Isaac.GetTrinketIdByName("Knife Pebble"),
	TEARDROP_PEBBLE 			= Isaac.GetTrinketIdByName("Teardrop Pebble"),
	ARROW_PEBBLE 				= Isaac.GetTrinketIdByName("Arrow Pebble"),
	CLOVER_PEBBLE 				= Isaac.GetTrinketIdByName("Clover Pebble"),
	SHOE_PEBBLE 				= Isaac.GetTrinketIdByName("Shoe Pebble"),
	FRUITY_PEBBLE 				= Isaac.GetTrinketIdByName("Fruity Pebble"),
	--Grimlins
	GRIMACE_ROCK1 				= Isaac.GetTrinketIdByName("Grimlin"),
	GRIMACE_ROCK2 				= Isaac.GetTrinketIdByName("Vomit Grimlin"),
	GRIMACE_ROCK3 				= Isaac.GetTrinketIdByName("Wetstone Grimlin"),
	GRIMACE_ROCK4 				= Isaac.GetTrinketIdByName("Constant Grimlin"),
	GRIMACE_ROCK5 				= Isaac.GetTrinketIdByName("Broken Gaping Grimlin"),
	GRIMACE_ROCK6 				= Isaac.GetTrinketIdByName("Brimlin"),
	GRIMACE_ROCK7 				= Isaac.GetTrinketIdByName("Cross Grimlin"),
	GRIMACE_ROCK8 				= Isaac.GetTrinketIdByName("Eye Grimlin"),
	GRIMACE_ROCK9 				= Isaac.GetTrinketIdByName("Cauldron Grimlin"),
	GRIMACE_ROCK10 				= Isaac.GetTrinketIdByName("Gaping Grimlin"),
	GRIMACE_ROCK11 				= Isaac.GetTrinketIdByName("Trimlin"),
	GRIMACE_ROCK12 				= Isaac.GetTrinketIdByName("Sensory Grimlin"),
	--Fossils
	BREAKFAST_FOSSIL 			= Isaac.GetTrinketIdByName("Breakfast Fossil"),
	SACK_FOSSIL 				= Isaac.GetTrinketIdByName("Sack Fossil"),
	COPROLITE_FOSSIL 			= Isaac.GetTrinketIdByName("Coprolite Fossil"),
	BEETER_FOSSIL 				= Isaac.GetTrinketIdByName("Beeter Fossil"),
	FLY_FOSSIL 					= Isaac.GetTrinketIdByName("Fly Fossil"),
	GMO_FOSSIL 					= Isaac.GetTrinketIdByName("GMO Fossil"),
	SWORD_FOSSIL 				= Isaac.GetTrinketIdByName("Sword Fossil"),
	FORTUNE_WORM_FOSSIL 		= Isaac.GetTrinketIdByName("Fortune Worm Fossil"),
	PRIMORDIAL_FOSSIL 			= Isaac.GetTrinketIdByName("Primordial Fossil"),
	REROLLIGAN_FOSSIL 			= Isaac.GetTrinketIdByName("Rerolligan Fossil"),
	FOSSILIZED_FOSSIL 			= Isaac.GetTrinketIdByName("Fossilized Fossil"),
	FISH_FOSSIL 				= Isaac.GetTrinketIdByName("Fish Fossil"),
	RUNIC_FOSSIL 				= Isaac.GetTrinketIdByName("Runic Fossil"),
	CANNED_FOSSIL 				= Isaac.GetTrinketIdByName("Canned Fossil"),
	BALANCED_FOSSIL 			= Isaac.GetTrinketIdByName("Balanced Fossil"),
	BURIED_FOSSIL 				= Isaac.GetTrinketIdByName("Buried Fossil"),
	TRIPPY_FOSSIL 				= Isaac.GetTrinketIdByName("Trippy Fossil"),
	MAXS_FOSSIL 				= Isaac.GetTrinketIdByName("Max's Fossil"),
	BOMB_SACK_FOSSIL 			= Isaac.GetTrinketIdByName("Bomb Sack Fossil"),
	DEATH_CAP_FOSSIL 			= Isaac.GetTrinketIdByName("Death Cap Fossil"),
	EXPLOSIVE_FOSSIL 			= Isaac.GetTrinketIdByName("Explosive Fossil"),
	COLOSSAL_FOSSIL 			= Isaac.GetTrinketIdByName("Colossal Fossil"),
	SKUZZ_FOSSIL 				= Isaac.GetTrinketIdByName("Skuzz Fossil"),
	FOSSILIZED_BLESSING 		= Isaac.GetTrinketIdByName("Fossilized Blessing"),
	PETRIFIED_SOCK 				= Isaac.GetTrinketIdByName("Petrified Sock"),
	MOLTEN_FOSSIL 				= Isaac.GetTrinketIdByName("Molten Fossil"),
	VALUE_FOSSIL 				= Isaac.GetTrinketIdByName("Value Fossil"),
	CORAL_FOSSIL 				= Isaac.GetTrinketIdByName("Coral Fossil"),
	NECROMANTIC_FOSSIL 			= Isaac.GetTrinketIdByName("Necromantic Fossil"),
	BRAIN_FOSSIL 				= Isaac.GetTrinketIdByName("Brain Fossil"),
	REFUND_FOSSIL 				= Isaac.GetTrinketIdByName("Refund Fossil"),
	LEFT_FOSSIL 				= Isaac.GetTrinketIdByName("The Left Fossil"),
	THANK_YOU_FOSSIL 			= Isaac.GetTrinketIdByName("Thank-You Fossil"),
	--Geodes
	CURVED_GEODE 				= Isaac.GetTrinketIdByName("Curved Geode"),
	HAUNTED_GEODE 				= Isaac.GetTrinketIdByName("Haunted Geode"),
	HEALTH_GEODE 				= Isaac.GetTrinketIdByName("Health Geode"),
	LITTLE_GEODE 				= Isaac.GetTrinketIdByName("Little Geode"),
	QUICK_GEODE 				= Isaac.GetTrinketIdByName("Quick Geode"),
	WEBBY_GEODE 				= Isaac.GetTrinketIdByName("Webby Geode"),
	LUCKY_GEODE 				= Isaac.GetTrinketIdByName("Lucky Geode"),
	PHLEGMY_GEODE 				= Isaac.GetTrinketIdByName("Phlegmy Geode"),
	LOB_GEODE 					= Isaac.GetTrinketIdByName("Lob Geode"),
	SODALITE_GEODE 				= Isaac.GetTrinketIdByName("Sodalite Geode"),
	PLACEBEODE 					= Isaac.GetTrinketIdByName("Placebeode"),
	WARM_GEODE 					= Isaac.GetTrinketIdByName("Warm Geode"),
	CHAIN_GEODE 				= Isaac.GetTrinketIdByName("Chain Geode"),
	RUSTY_GEODE 				= Isaac.GetTrinketIdByName("Rusty Geode"),
	FRAGMENTED_ONYX_GEODE 		= Isaac.GetTrinketIdByName("Fragmented Onyx Geode"),
	QUANTUM_GEODE 				= Isaac.GetTrinketIdByName("Quantum Geode"),
	TECHNOLOGICAL_GEODE 		= Isaac.GetTrinketIdByName("Technological Geode"),
	RUBBER_GEODE 				= Isaac.GetTrinketIdByName("Rubber Geode"),
	CALZONE_GEODE 				= Isaac.GetTrinketIdByName("Calzone Geode"),
	TOUGH_GEODE 				= Isaac.GetTrinketIdByName("Tough Geode"),
	TIPSY_GEODE 				= Isaac.GetTrinketIdByName("Tipsy Geode"),
	VINYL_GEODE_A 				= Isaac.GetTrinketIdByName("A-Side Vinyl Geode"),
	VINYL_GEODE_B 				= Isaac.GetTrinketIdByName("B-Side Vinyl Geode"),
	PRISMATIC_GEODE 			= Isaac.GetTrinketIdByName("Prismatic Geode"),
	FRACTAL_GEODE 				= Isaac.GetTrinketIdByName("Fractal Geode"),
	GMO_GEODE 					= Isaac.GetTrinketIdByName("GMO Geode"),
	SWALLOWED_GEODE 			= Isaac.GetTrinketIdByName("Swallowed Geode"),
	VOODOO_GEODE				= Isaac.GetTrinketIdByName("Voodoo Geode"),
	UMBILICAL_GEODE				= Isaac.GetTrinketIdByName("Umbilical Geode"),
	--The special one
	GEODE_FOSSIL 				= Isaac.GetTrinketIdByName("Geode Fossil"),
}

if EID then
	local iconSprite = Sprite()
	iconSprite:Load("gfx/ui/eid/eid_ff_icons.anm2", true)
	EID:addIcon("ffCrush", "Crush", 0, 24, 24, -1, 0, iconSprite)
	EID:addIcon("ffGrind", "Grind", 0, 24, 24, -1, 0, iconSprite)
end

__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.DIRT_CLUMP] = "#{{ffGrind}} Can be grinded for free#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ROLLING_ROCK] = "↑ 0.05 speed up after clearing a room without taking damage, caps at 0.15#Bonus resets upon entering a room after taking damage#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.POCKET_SAND] = "Does nothing#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ROUGH_ROCK] = "#{{ffGrind}} Guaranteed to grind into a rarer rock trinket#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.BLOODY_ROCK] = "Every 4th tear fired becomes a double damage blood tear#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SPIKED_ROCK] = "Damages the player for 1/2 heart on first pickup (non-fatal)#Blocks damage from spikes and spiked chests#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SLIPPY_ROCK] = "↑ +0.15 speed#Friction down#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ARCANE_ROCK] = "Tears have a chance to become homing, scales with luck#↑ +2 damage to homing tears#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.MINERAL_ROCK] = "↑ All stats up while actively pressing against rocks#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.THORNY_ROCK] = "Spawn a radial shockwave when damaged#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TIME_LOST_DIAMOND] = "Use Glowing Hourglass the first time hit in a room#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.OBSIDIAN_GRINDSTONE] = "↑ Damage up, tears up, boosted if holding another rock trinket#Every 30 tears, reroll the other held trinket#Extra effects do not apply to Pocket Sand#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GODS_MARBLE] = "Tears have a chance to apply the effect, scales with luck#Effect is an aura on the floor which spawns holy light when an enemy touches it#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TWENTY_SIDED_EMERALD] = "Standing still near a pickup rerolls it every 3 seconds#Any individual pickup can only be rerolled up to 3 times#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TECHNOLOGICAL_RUBY_2] = "Grants 2 laser rings at your position#The inner ring deals 10% damage#The outer ring deals 25% damage#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.LEAKY_ROCK] = "You now leave a trail of stationary tears while you move#Damage scales with your damage#Frequency scales with your Max-Firedelay#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TWIN_TUFFS] = "(25 + 2.5x Luck)% chance to turn pickups into their doubled equivalent#(15 + 1.5x Luck)% chance to double room rewards#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.WETSTONE] = "Periodically release friendly bubbles in uncleared rooms#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.STROMATOLITE] = "Rocks may drop a half heart when broken#Tinted and Secret rocks may instead drop an additional half soul heart#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.RIBBED_ROCK] = "Grants 1 bone heart on first pickup#Health upgrades grant bone hearts instead of heart containers#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FIENDISH_AMETHYST] = "On entering an uncleared room spawns four amethyst Fiend minions#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.STURDY_ROCK] = "Grants 1 soul heart at the start of a floor#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.BRICK_ROCK] = "Firing tears throws a 15 damage brick that drops on the floor afterwards#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SAPPHIC_SAPPHIRE] = "Charms female enemies#Occasionally fire freezing tears #!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.BLOOD_DIAMOND] = "Occasionally fire tears that cause bleed#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SCENTED_ROCK] = "Charms enemies in a small radius around the player.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ARCADE_ROCK] = "(25 + 2.5x Luck)% chance for coin machines to be free.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TINTED_HEART] = "Chance to drop red hearts when taking damage.#Drops soul hearts instead with explosive damage, along with a key, bomb, or chest.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ROSE_QUARTZ] = "Taking damage grants a temporary shield that blocks projectiles.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.HAILSTONE] = "Enemies close by the player are slowed, and frozen on death.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.RAMBLIN_OPAL] = "Spawns friendly Shiitake Spores as time goes on, with a maximum of 3 out at a time.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SAND_DOLLAR] = "Dropping the trinket in a shop exchanges it for 10-20 cents.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.HENGE_ROCK] = "Empowers every golem trinket you own by a small amount.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SALT_LAMP] = "Repels close by enemies and projectiles, but slowly drains in power over time. Can be recharged with batteries.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.MOLTEN_SLAG] = "Occasionally burns nearby enemies. When grinded, smelts your other trinket.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.THUNDER_EGG] = "\2 -0.1 speed#Each room has a chance for the Thunder Egg to crack open into another Rare or Fiendish rock.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.UNOBTAINIUM] = "Completely unobtainable, don't even try!"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SANDSTONE] = "Chance to fire a high damage rock that inflicts Blind and shrinks over time.#Turns into Pocket Sand when taking explosive damage.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FAKE_ROCK] = "Drops a key on pickup.#If there is a locked door, the first broken rock in the room drops a key.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.CITRINE_PULP] = "Small chance to fire a short ranged splash of tears.#When enemies are close, small chance to create a puddle of creep.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.BLOODSTONE] = "+0.2 damage whenever an enemy dies.#+1 damage when the player takes damage.#Damage bonuses decay over time.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.EMETIC_ANTIMONY] = "Periodically, gives the player Ipecac for one shot.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.DOUBLE_RUBBLE] = "#{{ffGrind}} Grinds into two common or rare rocks.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ROCK_FROM_AN_ABYSS] = "20% chance to apply Doom to 3 enemies at the start of the room.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.HECTOR] = "↑ Damage and tears up#↓ Speed down#Forcibly dropped when taking damage.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.VESSEL_ROCK] = "Stores an extra heart#Does not count against devil deal chance#Breaks when taking damage while empty.#Empty#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.HALF_VESSEL_ROCK] = "Stores an extra heart#Does not count against devil deal chance#Breaks when taking damage while empty.#Halfway filled#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FULL_VESSEL_ROCK] = "Stores an extra heart#Does not count against devil deal chance#Breaks when taking damage while empty.#Full#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.CONSTANT_ROCK_SHOOTER] = "↑ Large tears up.#The player never stops firing.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ROBOT_ROCK] = "Grants the player spinning lasers that inflict random status effects.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ROCK_CANDY] = "Chance to fire crystal tears that charm and deal 1.5x damage.#Enemies have a small chance to drop a sugar crystal on death that heals half a heart, but fades after time.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.KEYSTONE] = "Grants a minor tears and speed up for the floor whenever the player uses a key.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SILVER_TONGUE] = "The Mining Machine costs 1 less cent.#When smelted, has a 50% chance to activate.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.MEAT_SLAB] = "The player constantly sweats out arced tears that have a chance to inflict Sweating.#Sweating rate increases based on how low the player's HP is in comparison to their max red hearts.#Chance to fire a tear that inflicts Sweating.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SHEEP_ROCK] = "Chance to fire a Drowsy tear that decellerates and floats in place.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.REBELLION_ROCK] = "When taking damage, deals minor damage to all nearby enemies, knocks them back, and inflicts them with Bruise.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.DADS_LEGENDARY_GOLDEN_ROCK] = "Always gold!#{{ffGrind}} When grinding, always grants a golden rare or better rock.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.BEDROCK] = "1/3 Chance for a bed to spawn at the start of every floor.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SHEETROCK] = "Heal 2 hearts at the start of each floor.#Sleeping in a bed grants 2 extra soul hearts.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FETAL_STONE] = "Grants a rock familiar that fires rock tears that have a chance to confuse.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRIMACE_ROCK1] = "Fires tears at nearby enemies.#Also works when dropped.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRIMACE_ROCK2] = "Fires arced explosive shots at nearby enemies.#Also works when dropped.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRIMACE_ROCK3] = "Passively spawns small bubbles that deal damage and block shots.#Also works when dropped.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRIMACE_ROCK4] = "Constantly fires in a random direction.#Also works when dropped.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRIMACE_ROCK5] = "Periodically begins sucking in all nearby enemies.#Also works when dropped.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRIMACE_ROCK6] = "Periodically fires brimstone beams in a random direction.#Also works when dropped.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRIMACE_ROCK7] = "Constantly fires in a +, then x.#Also works when dropped.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRIMACE_ROCK8] = "Constantly fires a rotating laser.#Also works when dropped.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRIMACE_ROCK9] = "Periodically spawns a friendly copy of an enemy in the room#Also works when dropped.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRIMACE_ROCK10] = "Constantly sucks in pickups.#Also works when dropped.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRIMACE_ROCK11] = "Fires a triple shot at nearby enemies.#Also works when dropped.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRIMACE_ROCK12] = "Walking in a set direction causes the grimace to fire in that direction.#Also works when dropped.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FOCUS_CRYSTAL] = "Increase damage to enemies within {{ColorYellow}}2.5 tiles{{CR}} by {{ColorYellow}}20%{{CR}} {{ColorGray}}(+20% per stack).{{CR}}#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ODDLY_SMOOTH_STONE] = "Start each combat with {{ColorCyan}}1{{CR}} {{ColorYellow}}Dexterity.{{CR}}#Dexterity improves life gained from hearts.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.MOONSTONE] = "Grants a luck, range, tears, or shotspeed up when entering a secret room.#Bonuses only applied while holding the trinket.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.LIMESTONE] = "Leave a trail of lime creep that deals 50% damage.#Permanently charms citrus related enemies.#More limes?#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.CARNAL_CARNELIAN] = "Gain damage and speed depending on how close the player is to enemies.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.REBAR_ROCK] = "25% chance to block red heart damage.#Red heart damage is always half a heart.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.STALACTITE] = "Explosions cause rocks that deal 2x tear damage to fall from the sky randomly.#Falling rock projectiles are turned friendly.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.CAST_GEM] = "Grants a homing gem that can be cast while attacking and sticks to enemies, inflicting damage and bruising#Bruised enemies take bonus damage from all sources of damage based on the number of stacks applied#Has special synergies with certain items#{{Collectible"..CollectibleType.COLLECTIBLE_NYX.."}} Same gem granted by the 'Nyx' item#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SHARD_OF_GOLGOTHA] = "Chains the highest health enemy at the start of every room.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SMOKY_QUARTZ] = "Blinds nearby enemies and grants a decaying speed boost upon taking damage.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TWINKLING_ROCK] = "#{{ffGrind}} Grinds into a common or rare geode.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ROCK_CAKE] = "#{{ffGrind}} Grinding heals half a red heart.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.CHARCOAL] = "Chance to fire a very slow projectile that grows in size and damage over time.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.KNIFE_PEBBLE] = "↑ +1.25 damage#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TEARDROP_PEBBLE] = "↑ +1.65 tears#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ARROW_PEBBLE] = "↑ +1.25 range, +0.2 shotspeed#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.CLOVER_PEBBLE] = "↑ +2 luck#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SHOE_PEBBLE] = "↑ +0.3 speed#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FRUITY_PEBBLE] = "↑ All stats up#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ACHILLES_ROCK] = "Enemies gain a random weak point. When damaged from that direction, they take 1.5x damage.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ELECTRUM] = "Using an active item shocks all nearby enemies.#Damage scales with charge amount and player damage.!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.PURE_QUARTZ] = "Losing all soul hearts grants a holy mantle shield and invulnerability for a period.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.AMAZONITE] = "The first pickup every floor costs 1 cent but disappears when bought.#These pickups are spawned at the start of the next floor.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.STAR_SAPPHIRE] = "Grants a familiar that wobbily points towards the nearest enemy or projectile.#Blocks shots and deals contact damage.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GRAVESTONE] = "Taking damage spawns a purgatory ghost or hungry soul.#Chance for broken rocks to spawn a soul as well.!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SAND_CASTLE] = "Can block 3 hits before breaking into Pocket Sand.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.DAMAGED_SAND_CASTLE] = "Can block 2 hits before breaking into Pocket Sand.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.BROKEN_SAND_CASTLE] = "Can block 1 hit before breaking into Pocket Sand.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GUARDED_GARNET] = "Chance to gain a shield on damage that lasts for a room and blocks one hit#When blocked, knocks back enemies nearby.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SHAMROCK] = "↑ +4 Luck.#When taking damage, lose 1 luck for the floor.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GAS_POCKET] = "Rocks occasionally leak gas.#When broken, rocks have a chance to spawn large clouds of gas#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SOAP_STONE] = "Clears all projectiles on room clear and when taking damage.#Spawns several bubbles upon taking damage.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SPIRIT_URN] = "Grants 3 wisps when entering a boss or miniboss room.#Grants 3 wisps when starting a challenge room.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SUN_SHARD] = "Grants a Sun planet as an orbital which have special effects when blocking shots.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.STEADFAST_STONE] = "When taking lethal damage, instead crushes a trinket you're actively holding.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.RAI_STONE] = "15% chance for enemies to drop a temporary penny on death.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ORE_PENNY] = "50% chance to gain an extra cent when picking up coins.#Chance to replace rocks with Fool's Gold.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.HEAVY_METAL] = "↓ 0.15 Speed down.#Grants a damage up that scales off of how slow the player is.#Chance to block damage that scales with how slow the player is.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GROSSULAR] = "Periodically fire a pulse that either fears, poisons, or confuses enemies nearby.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SULFUR_CRYSTAL] = "Grants Brimstone at the start of every 4th room.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TROLLITE] = "We do a little trolling.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.THROWLOMITE] = "Periodically tosses a rock at the nearest enemy in a short distance.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.HEARTHSTONE] = "Activates a random positive effect when using a card.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.MAGNETIC_SAND] = "↑0.45 tears up#↓0.35 damage down#Chance to fire a tear that makes enemies magnetic.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.INSATIABLE_APATITE] = "Gain a temporary damage up when picking up hearts.#When full on hearts, can destroy them to gain double the damage.#Some hearts have special effects.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.POWER_ROCK] = "Breaking rocks has a small chance to restore an active charge.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TIGERS_EYE] = "Spawns a Tiger's Eye familiar that bounces around the room, dealing contact damage and blocking shots.#Bounces directly towards the closest enemy.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SMALLER_ROCK] = "Bombing a tinted rock gives -0.06 speed down and +0.33 damage.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.NITRO_CRYSTAL] = "Picking up pennies fuels your nitro#Your nitro gives you a speed and tears up while active#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SHARD_OF_GOLEM] = "Grants a special bar that charges by overhealing#Grants +0.45 damage for each heart filled in the bar#Once all hearts are filled both held trinkets are smelted#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.ROCK_WORM] = "↑0.4 tears up#↑0.4 damage up#Grants a random worm trinket effect at the start of the floor for the duration of the floor#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FOOLS_UNOBTAINIUM] = "Supposedly unobtainable, but it's not hard to actually get.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.MINICHIBISIDIAN] = "Randomly replaces enemies with bonies of equivalent health.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FRIENDLY_RAPID_FIRE_OPAL] = "Start each room with a limited ammo assault rifle with increased tear rate, range and shotspeed.#!!! Rock Trinket"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.HIDDENITE] = "Entering then breaking the line of sight from an enemy for the first time confuses them for a period.#!!! Rock Trinket"

__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.BREAKFAST_FOSSIL] = "#{{ffCrush}} ↑ +1 max health when crushed#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SACK_FOSSIL] = "Chance to reroll pickups into sacks#{{ffCrush}} Spawns a sack when crushed#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.COPROLITE_FOSSIL] = "Spawns a blue fly each new room#{{ffCrush}} Spawns 12 blue flies when crushed#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.BEETER_FOSSIL] = "Fire a single weak tear when a tear is fired#Increments its angle each time#{{ffCrush}} Spawns a friendly Beeter when crushed#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FLY_FOSSIL] = "Spawns a Famine Locust each new room#{{ffCrush}} Gives a Pretty Fly when crushed#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GMO_FOSSIL] = "Activates 2 random pill effects after beating a boss#{{ffCrush}} Activates 3 random pill effects when crushed#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SWORD_FOSSIL] = "↑ All stats up#{{ffCrush}} ↑ Smaller permanent all stats up when crushed#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FORTUNE_WORM_FOSSIL] = "Fortune Worm effect#↑ +0.2 Shotspeed, +2 Luck (From {{Trinket"..TrinketType.TRINKET_FORTUNE_WORM.."}})#{{ffCrush}} Spawns an extra soul heart, and displays 3 random fortunes when crushed#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.PRIMORDIAL_FOSSIL] = "1/15 chance to fire a small barrage of Mysterious Liquid tears instead of a normal tear#{{ffCrush}} Grants Golem's starting fossils when crushed ({{Trinket"..FiendFolio.ITEM.ROCK.DIRT_CLUMP.."}} + {{Trinket"..FiendFolio.ITEM.ROCK.ROLLING_ROCK.."}})#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.REROLLIGAN_FOSSIL] = "Tears have a chance to reroll enemies#{{ffCrush}} Spawns glass dice when crushed#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FOSSILIZED_FOSSIL] = "Other fossil's crushing effects activate twice.#{{ffCrush}} Activates the effect of another held fossil when crushed#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FISH_FOSSIL] = "Spawn 1-4 blue flies when damaged.#{{ffCrush}} Spawns a friendly portal when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.RUNIC_FOSSIL] = "Runes are more common.#Using runes drops a rune shard.#{{ffCrush}} Drops 4 rune shards when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.CANNED_FOSSIL] = "Isaac farts when taking damage.#{{ffCrush}} Spawns a friendly Charmed Litter bug when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.BALANCED_FOSSIL] = "50% chance for the room clear reward to be replaced by a heart/coin/bomb/key, if you have little.#{{ffCrush}} Grants 3 of your lowest pickup when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.BURIED_FOSSIL] = "Each floor has a marked spot that can be bombed to spawn a fossil.#{{ffCrush}} Gives a random fossil when crushed#Dirt patches can be bombed open.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TRIPPY_FOSSIL] = "Chance to fire God's Flesh tears.#{{ffCrush}} Shrinks the player when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.MAXS_FOSSIL] = "Howls when next to a secret room.#{{ffCrush}} When crushed, the next tinted rock the player encounters is revealed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.BOMB_SACK_FOSSIL] = "The player's bombs create a ring of rock waves.#{{ffCrush}} Spawns 5 bombs when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.DEATH_CAP_FOSSIL] = "\2 Stacking minor stats down on each room.#{{ffCrush}} ↑ All stats up when crushed proportional to cleared rooms.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.EXPLOSIVE_FOSSIL] = "Chance to drop an extra bomb on room clear.#Chance for rocks to be replaced with bomb rocks.#{{ffCrush}} When crushed, grants the Mama Mega effect for the next 3 uncleared rooms.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.COLOSSAL_FOSSIL] = "Doubles the player's tear size.#{{ffCrush}} When crushed, activates 3 random fossil effects.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SKUZZ_FOSSIL] = "Spawn 2-3 fleas of Pollution at the start of rooms.#{{ffCrush}} Spawns 5-7 attack skuzzes when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FOSSILIZED_BLESSING] = "↑ 0.4 tears up#{{ffCrush}} Grants a random rock trinket at the start of your next run when crushed#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.PETRIFIED_SOCK] = "Chance to fire petrifying tears.#{{ffCrush}} Grants a random baby when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.MOLTEN_FOSSIL] = "Passively improves smelted rocks.#{{ffCrush}} Gives and smelts a random common rock when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.VALUE_FOSSIL] = "Shop items are 1 cent cheaper.#{{ffCrush}} Spawns 3 pennies when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.CORAL_FOSSIL] = "Chance to fire in an x shape.#Heals a heart on pickup.#{{ffCrush}} When crushed, spawns 3 friendly drowned chargers and heals a heart.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.NECROMANTIC_FOSSIL] = "Chance to spawn a bone orbital when killing an enemy.#{{ffCrush}} When crushed, grants a fossil that has been crushed this run.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.BRAIN_FOSSIL] = "Grants tears homing for a short period after being fired.#{{ffCrush}} Spawns a Magician card when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.REFUND_FOSSIL] = "Crushing other fossils grants Pocket Sand.#{{ffGrind}} Pocket Sands can be grinded for free.#{{ffCrush}} Spawns 2 Pocket Sands when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.LEFT_FOSSIL] = "All chests get replaced with red chests.#{{ffCrush}} Spawns a red chest when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.THANK_YOU_FOSSIL] = "Beggars pay out twice#{{ffCrush}} Spawns a judgement card when crushed.#!!! Rock Trinket {{ColorRed}}(Fossil){{CR}}"

__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.CURVED_GEODE] = "↑ +1 damage#↑ +0.5 extra damage if holding another Geode#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.HAUNTED_GEODE] = "Chance for spectral+piercing tears, scales with luck#Increased chance if holding another Geode#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.HEALTH_GEODE] = "When the player drops to 1 red heart or less, heals red hearts and breaks#+1 soul heart if holding another Geode#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.LITTLE_GEODE] = "Size down#Extra size down if holding another Geode#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.QUICK_GEODE] = "↑ Boosts speed to 1.75 in cleared rooms#+0.10 speed up if holding another Geode#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.WEBBY_GEODE] = "(20 + 2x Luck) % chance to fire a slowing tear#Slowing tears leave large puddles of white creep if they hit an enemy while you're holding another Geode#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.LUCKY_GEODE] = "↑ +1 Luck#↑ Bonus +2 Luck if holding another Geode#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.PHLEGMY_GEODE] = "(10 + Luck) % chance to fire a booger tear#Booger tears gain slowing if holding another geode#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.LOB_GEODE] = "↑ +6 range#↑ +3 extra range if holding another Geode#Tears are now shot in an arc#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SODALITE_GEODE] = "Luck-affected chance to shoot crit tears that deal quintuple damage#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.PLACEBEODE] = "Permanent geode bonus when smelted#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.WARM_GEODE] = "↑ Damage and Shotspeed up when near a fire#If holding another Geode, tears also inflict burn when standing near a fire#Warm floors give a passive stat buff.!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.CHAIN_GEODE] = "Broken Rocks have a 40% chance to break nearby rocks#Nearby rocks have a 70% chance to break, along with a 20% chance for pits to fill with another geode#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.RUSTY_GEODE] = "↑ +6 Damage that decays over time#If holding another Geode, decays at a slower rate#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FRAGMENTED_ONYX_GEODE] = "10% chance to inflict fear.#If holding another Geode, increases to 15% chance and feared enemies take extra damage equal to the Devil Deal chance.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.QUANTUM_GEODE] = "Fire in a triple shot.#Once a tear hits an enemy, the rest vanish.#If holding another geode, the tears vanish once two land.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TECHNOLOGICAL_GEODE] = "Fire a short ranged technology 2 beam that deals 30% damage.#If holding another geode, fire 2 parallel beams instead.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.RUBBER_GEODE] = "Chance to fire bouncing tennis balls that inflict bruise and deal knockback.#If holding another geode, higher chance to fire as well as more knockback and shot speed.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.CALZONE_GEODE] = "Chance to fire a chubber shot that inflicts Baited and boomerangs back.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TOUGH_GEODE] = "Chance to not destroy a rock upon crushing.#With another held geode, increases chances.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.TIPSY_GEODE] = "Grants a damage up and the player's movement slowly shifts about randomly.#With another geode, increases damage and movement.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.VINYL_GEODE_A] = "Increases damage and shotspeed.#Flips to the B Side on the first floor of the chapter which increases tears and speed.#With another geode, grants a minor tears and speed up.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.VINYL_GEODE_B] = "Increases tears and speed.#Flips to the A Side on second floor of the chapter which increases damage and shotspeed.#With another geode, grants a minor damage and shotspeed up.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.PRISMATIC_GEODE] = "Chance for enemies to drop Prism Shards on death that boost a random stat for 10 seconds.#Chance to drop an extra shard on room clear.#Shard duration is increased by 5 seconds and doubled in potency if holding another geode.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.FRACTAL_GEODE] = "Chance to fire a spiralling shot that inflicts Drowsy.#With another held geode, higher odds and shot has a chance to immediately inflict sleep.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GMO_GEODE] = "Taking a pill will also take a second random pill.#Also take an additional positive pill if holding two geodes.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.SWALLOWED_GEODE] = "Spawn a penny when damaged.#When holding another geode, gain a chance to spawn a doubled penny.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.VOODOO_GEODE] = "↑ +1.5 damage when a curse is present on the floor.#↑+0.35 damage for the floor when entering a curse room for the first time.#Damage boost multipled by 1.5 with another geode.#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"
__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.UMBILICAL_GEODE] = "Chance to spawn a Gemini Familiar when taking damage.#Gain a Little Steven familiar for the room when entering with half a heart or less.#With another geode, Gemini chances are improved and Little Steven can spawn at one heart or less#!!! Rock Trinket {{ColorTeal}}(Geode){{CR}}"

__eidTrinketDescriptions[FiendFolio.ITEM.ROCK.GEODE_FOSSIL] = "↑ +8 range#↑ +5 extra range if holding another Geode#{{ffCrush}} Gives a common or rare Geode trinket when crushed#{{ffCrush}} Gives an additional common or rare Geode trinket when crushed, if holding another Geode#!!! Rock Trinket ({{ColorTeal}}Geode{{CR}} x {{ColorRed}}Fossil{{CR}})"

--ENCYCLOPEDIA
if Encyclopedia then
	--Trinkets
	local EncycloTrinkets = {
		{ID = FiendFolio.ITEM.ROCK.DIRT_CLUMP},
		{ID = FiendFolio.ITEM.ROCK.ROLLING_ROCK},
		{ID = FiendFolio.ITEM.ROCK.POCKET_SAND},
		{ID = FiendFolio.ITEM.ROCK.ROUGH_ROCK},
		{ID = FiendFolio.ITEM.ROCK.BLOODY_ROCK},
		{ID = FiendFolio.ITEM.ROCK.SPIKED_ROCK},
		{ID = FiendFolio.ITEM.ROCK.SLIPPY_ROCK},
		{ID = FiendFolio.ITEM.ROCK.ARCANE_ROCK},
		{ID = FiendFolio.ITEM.ROCK.MINERAL_ROCK},
		{ID = FiendFolio.ITEM.ROCK.THORNY_ROCK},
		{ID = FiendFolio.ITEM.ROCK.TIME_LOST_DIAMOND},
		{ID = FiendFolio.ITEM.ROCK.OBSIDIAN_GRINDSTONE},
		{ID = FiendFolio.ITEM.ROCK.GODS_MARBLE},
		{ID = FiendFolio.ITEM.ROCK.TWENTY_SIDED_EMERALD},
		{ID = FiendFolio.ITEM.ROCK.TECHNOLOGICAL_RUBY_2},
		{ID = FiendFolio.ITEM.ROCK.LEAKY_ROCK},
		{ID = FiendFolio.ITEM.ROCK.TWIN_TUFFS},
		{ID = FiendFolio.ITEM.ROCK.WETSTONE},
		{ID = FiendFolio.ITEM.ROCK.STROMATOLITE},
		{ID = FiendFolio.ITEM.ROCK.RIBBED_ROCK},
		{ID = FiendFolio.ITEM.ROCK.FIENDISH_AMETHYST},
		{ID = FiendFolio.ITEM.ROCK.STURDY_ROCK},
		{ID = FiendFolio.ITEM.ROCK.BRICK_ROCK},
		{ID = FiendFolio.ITEM.ROCK.SAPPHIC_SAPPHIRE},
		{ID = FiendFolio.ITEM.ROCK.BLOOD_DIAMOND},
		{ID = FiendFolio.ITEM.ROCK.SCENTED_ROCK},
		{ID = FiendFolio.ITEM.ROCK.ARCADE_ROCK},
		{ID = FiendFolio.ITEM.ROCK.TINTED_HEART},
		{ID = FiendFolio.ITEM.ROCK.ROSE_QUARTZ},
		{ID = FiendFolio.ITEM.ROCK.HAILSTONE},
		{ID = FiendFolio.ITEM.ROCK.RAMBLIN_OPAL},
		{ID = FiendFolio.ITEM.ROCK.SAND_DOLLAR},
		{ID = FiendFolio.ITEM.ROCK.HENGE_ROCK},
		{ID = FiendFolio.ITEM.ROCK.SALT_LAMP},
		{ID = FiendFolio.ITEM.ROCK.MOLTEN_SLAG},
		{ID = FiendFolio.ITEM.ROCK.THUNDER_EGG},
		{ID = FiendFolio.ITEM.ROCK.SANDSTONE},
		{ID = FiendFolio.ITEM.ROCK.FAKE_ROCK},
		{ID = FiendFolio.ITEM.ROCK.CITRINE_PULP},
		{ID = FiendFolio.ITEM.ROCK.BLOODSTONE},
		{ID = FiendFolio.ITEM.ROCK.EMETIC_ANTIMONY},
		{ID = FiendFolio.ITEM.ROCK.DOUBLE_RUBBLE},
		{ID = FiendFolio.ITEM.ROCK.ROCK_FROM_AN_ABYSS},
		{ID = FiendFolio.ITEM.ROCK.VESSEL_ROCK},
		{ID = FiendFolio.ITEM.ROCK.HALF_VESSEL_ROCK, Hide = true},
		{ID = FiendFolio.ITEM.ROCK.FULL_VESSEL_ROCK, Hide = true},
		{ID = FiendFolio.ITEM.ROCK.CONSTANT_ROCK_SHOOTER},
		{ID = FiendFolio.ITEM.ROCK.ROBOT_ROCK},
		{ID = FiendFolio.ITEM.ROCK.ROCK_CANDY},
		{ID = FiendFolio.ITEM.ROCK.KEYSTONE},
		{ID = FiendFolio.ITEM.ROCK.SILVER_TONGUE},
		{ID = FiendFolio.ITEM.ROCK.MEAT_SLAB},
		{ID = FiendFolio.ITEM.ROCK.SHEEP_ROCK},
		{ID = FiendFolio.ITEM.ROCK.REBELLION_ROCK},
		{ID = FiendFolio.ITEM.ROCK.HECTOR},
		{ID = FiendFolio.ITEM.ROCK.DADS_LEGENDARY_GOLDEN_ROCK},
		{ID = FiendFolio.ITEM.ROCK.BEDROCK},
		{ID = FiendFolio.ITEM.ROCK.SHEETROCK},
		{ID = FiendFolio.ITEM.ROCK.FETAL_STONE},
		{ID = FiendFolio.ITEM.ROCK.FOCUS_CRYSTAL},
		{ID = FiendFolio.ITEM.ROCK.ODDLY_SMOOTH_STONE},
		{ID = FiendFolio.ITEM.ROCK.MOONSTONE},
		{ID = FiendFolio.ITEM.ROCK.LIMESTONE},
		{ID = FiendFolio.ITEM.ROCK.CARNAL_CARNELIAN},
		{ID = FiendFolio.ITEM.ROCK.REBAR_ROCK},
		{ID = FiendFolio.ITEM.ROCK.DOGROCK_ROCK},
		{ID = FiendFolio.ITEM.ROCK.CAST_GEM},
		{ID = FiendFolio.ITEM.ROCK.STALACTITE},
		{ID = FiendFolio.ITEM.ROCK.SHARD_OF_GOLGOTHA},
		{ID = FiendFolio.ITEM.ROCK.SMOKY_QUARTZ},
		{ID = FiendFolio.ITEM.ROCK.TWINKLING_ROCK},
		{ID = FiendFolio.ITEM.ROCK.ROCK_CAKE},
		{ID = FiendFolio.ITEM.ROCK.CHARCOAL},
		{ID = FiendFolio.ITEM.ROCK.ACHILLES_ROCK},
		{ID = FiendFolio.ITEM.ROCK.ELECTRUM},
		{ID = FiendFolio.ITEM.ROCK.PURE_QUARTZ},
		{ID = FiendFolio.ITEM.ROCK.AMAZONITE},
		{ID = FiendFolio.ITEM.ROCK.STAR_SAPPHIRE},
		{ID = FiendFolio.ITEM.ROCK.GRAVESTONE},
		{ID = FiendFolio.ITEM.ROCK.SAND_CASTLE},
		{ID = FiendFolio.ITEM.ROCK.DAMAGED_SAND_CASTLE, Hide = true},
		{ID = FiendFolio.ITEM.ROCK.BROKEN_SAND_CASTLE, Hide = true},
		{ID = FiendFolio.ITEM.ROCK.GUARDED_GARNET},
		{ID = FiendFolio.ITEM.ROCK.SHAMROCK},
		{ID = FiendFolio.ITEM.ROCK.GAS_POCKET},
		{ID = FiendFolio.ITEM.ROCK.SOAP_STONE},
		{ID = FiendFolio.ITEM.ROCK.SPIRIT_URN},
		{ID = FiendFolio.ITEM.ROCK.SUN_SHARD},
		{ID = FiendFolio.ITEM.ROCK.STEADFAST_STONE},
		{ID = FiendFolio.ITEM.ROCK.INSATIABLE_APATITE},
		{ID = FiendFolio.ITEM.ROCK.RAI_STONE},
		{ID = FiendFolio.ITEM.ROCK.ORE_PENNY},
		{ID = FiendFolio.ITEM.ROCK.HEAVY_METAL},
		{ID = FiendFolio.ITEM.ROCK.GROSSULAR},
		{ID = FiendFolio.ITEM.ROCK.SULFUR_CRYSTAL},
		{ID = FiendFolio.ITEM.ROCK.THROWLOMITE},
		{ID = FiendFolio.ITEM.ROCK.HEARTHSTONE},
		{ID = FiendFolio.ITEM.ROCK.MAGNETIC_SAND},
		{ID = FiendFolio.ITEM.ROCK.POWER_ROCK},
		{ID = FiendFolio.ITEM.ROCK.TIGERS_EYE},
		{ID = FiendFolio.ITEM.ROCK.SMALLER_ROCK},
		{ID = FiendFolio.ITEM.ROCK.SHARD_OF_GOLEM},
		{ID = FiendFolio.ITEM.ROCK.ROCK_WORM},
		{ID = FiendFolio.ITEM.ROCK.NITRO_CRYSTAL},
		{ID = FiendFolio.ITEM.ROCK.FOOLS_UNOBTAINIUM},
		{ID = FiendFolio.ITEM.ROCK.MINICHIBISIDIAN},
		{ID = FiendFolio.ITEM.ROCK.FRIENDLY_RAPID_FIRE_OPAL},
		{ID = FiendFolio.ITEM.ROCK.HIDDENITE},
		
		{ID = FiendFolio.ITEM.ROCK.REROLLIGAN_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.BREAKFAST_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.SACK_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.COPROLITE_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.BEETER_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.FLY_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.GMO_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.SWORD_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.FORTUNE_WORM_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.PRIMORDIAL_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.FOSSILIZED_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.FISH_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.RUNIC_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.CANNED_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.BALANCED_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.BURIED_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.TRIPPY_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.MAXS_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.BOMB_SACK_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.DEATH_CAP_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.EXPLOSIVE_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.COLOSSAL_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.SKUZZ_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.MOLTEN_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.VALUE_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.CORAL_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.NECROMANTIC_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.BRAIN_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.PETRIFIED_SOCK},
		{ID = FiendFolio.ITEM.ROCK.REFUND_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.LEFT_FOSSIL},
		{ID = FiendFolio.ITEM.ROCK.FOSSILIZED_BLESSING},
		{ID = FiendFolio.ITEM.ROCK.THANK_YOU_FOSSIL},
		
		{ID = FiendFolio.ITEM.ROCK.CURVED_GEODE},
		{ID = FiendFolio.ITEM.ROCK.HAUNTED_GEODE},
		{ID = FiendFolio.ITEM.ROCK.HEALTH_GEODE},
		{ID = FiendFolio.ITEM.ROCK.LITTLE_GEODE},
		{ID = FiendFolio.ITEM.ROCK.QUICK_GEODE},
		{ID = FiendFolio.ITEM.ROCK.WEBBY_GEODE},
		{ID = FiendFolio.ITEM.ROCK.LUCKY_GEODE},
		{ID = FiendFolio.ITEM.ROCK.PHLEGMY_GEODE},
		{ID = FiendFolio.ITEM.ROCK.LOB_GEODE},
		{ID = FiendFolio.ITEM.ROCK.SODALITE_GEODE},
		{ID = FiendFolio.ITEM.ROCK.PLACEBEODE},
		{ID = FiendFolio.ITEM.ROCK.WARM_GEODE},
		{ID = FiendFolio.ITEM.ROCK.CHAIN_GEODE},
		{ID = FiendFolio.ITEM.ROCK.RUSTY_GEODE},
		{ID = FiendFolio.ITEM.ROCK.FRAGMENTED_ONYX_GEODE},
		{ID = FiendFolio.ITEM.ROCK.QUANTUM_GEODE},
		{ID = FiendFolio.ITEM.ROCK.TECHNOLOGICAL_GEODE},
		{ID = FiendFolio.ITEM.ROCK.RUBBER_GEODE},
		{ID = FiendFolio.ITEM.ROCK.CALZONE_GEODE},
		{ID = FiendFolio.ITEM.ROCK.TOUGH_GEODE},
		{ID = FiendFolio.ITEM.ROCK.TIPSY_GEODE},
		{ID = FiendFolio.ITEM.ROCK.VINYL_GEODE_A},
		{ID = FiendFolio.ITEM.ROCK.VINYL_GEODE_B, Hide = true},
		{ID = FiendFolio.ITEM.ROCK.PRISMATIC_GEODE},
		{ID = FiendFolio.ITEM.ROCK.GMO_GEODE},
		{ID = FiendFolio.ITEM.ROCK.FRACTAL_GEODE},
		{ID = FiendFolio.ITEM.ROCK.SWALLOWED_GEODE},
		{ID = FiendFolio.ITEM.ROCK.VOODOO_GEODE},
		{ID = FiendFolio.ITEM.ROCK.UMBILICAL_GEODE},
		{ID = FiendFolio.ITEM.ROCK.GEODE_FOSSIL},
		
		{ID = FiendFolio.ITEM.ROCK.KNIFE_PEBBLE},
		{ID = FiendFolio.ITEM.ROCK.TEARDROP_PEBBLE},
		{ID = FiendFolio.ITEM.ROCK.ARROW_PEBBLE},
		{ID = FiendFolio.ITEM.ROCK.CLOVER_PEBBLE},
		{ID = FiendFolio.ITEM.ROCK.SHOE_PEBBLE},
		{ID = FiendFolio.ITEM.ROCK.FRUITY_PEBBLE},
		
		{ID = FiendFolio.ITEM.ROCK.GRIMACE_ROCK1},
		{ID = FiendFolio.ITEM.ROCK.GRIMACE_ROCK2},
		{ID = FiendFolio.ITEM.ROCK.GRIMACE_ROCK3},
		{ID = FiendFolio.ITEM.ROCK.GRIMACE_ROCK4},
		{ID = FiendFolio.ITEM.ROCK.GRIMACE_ROCK5},
		{ID = FiendFolio.ITEM.ROCK.GRIMACE_ROCK6},
		{ID = FiendFolio.ITEM.ROCK.GRIMACE_ROCK7},
		{ID = FiendFolio.ITEM.ROCK.GRIMACE_ROCK8},
		{ID = FiendFolio.ITEM.ROCK.GRIMACE_ROCK9},
		{ID = FiendFolio.ITEM.ROCK.GRIMACE_ROCK10},
		{ID = FiendFolio.ITEM.ROCK.GRIMACE_ROCK11},
		{ID = FiendFolio.ITEM.ROCK.GRIMACE_ROCK12},
		
		{ID = FiendFolio.ITEM.ROCK.TROLLITE, Hide = true},
		{ID = FiendFolio.ITEM.ROCK.UNOBTAINIUM, Hide = true},
	}

	for _, info in pairs(EncycloTrinkets) do
		Encyclopedia.AddTrinket({
			Class = "Golem's Rocks",
			ID = info.ID,
			WikiDesc = Encyclopedia.EIDtoWiki(__eidTrinketDescriptions[info.ID] or ""),
			--UnlockFunc = EncycloItems[id].Unlock,
			Hide = info.Hide,
			ModName = "Fiend Folio",
		})
	end
end
